### ISSUE TITLE
쇼핑몰을 만들어보세요

### ISSUE THREAD

**Issue by won98** [jpark1125/Node.js_CRUD#1]
쇼핑몰을 만들어보세요
제가 이야기했던거 주의해서 그리고
비밀번호 암호화 하는 모듈 있어요 아주 유명하고 가장 많이쓰는거 그것도 적용해서 한번 해보세용

**Comment by jpark1125** [comment]
네~~

**Comment by won98** [comment]
좋아요
어떄요 이슈 떄려지니깐ㅋㅋㅋㅋㅋ

**Comment by jpark1125** [comment]
메일로 뭐가 날라와서 깜짝놀랐어요 ㅎ

**Comment by won98** [comment]
어디까지햇어
